resources:
- repo: self
pool:
  name: Edlund-dev on-premises OS2019-VS2019
#Your build pipeline references a secret variable named ‘client_secret’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘managed_image_prefix’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

jobs:

- job: "BuildPackerVM"
  timeoutInMinutes: 0
  steps:
  - task: PackerBuild@1  
    inputs:
      templateType: 'custom'
      customTemplateLocation: 'images\win\vs2019-Server2019-Azure.json'
      customTemplateParameters: '{"client_id":"$(spClientId)","client_secret":"$(spClientSecret)","subscription_id":"$(subscriptionId)","tenant_id":"$(tenantId)","object_id":"$(spObjectId)","location":"$(location)","resource_group":"$(rgName)","storage_account":"$(storageAccountName)","install_password":"$(installPassword)"}'
      #customTemplateParameters: '{"install_password":"$(install_password)","client_id":"$(client_id)","client_secret":"$(client_secret)","tenant_id":"$(tenant_id)","subscription_id":"$(subscription_id)","build_resource_group_name":"$(resource_group)","storage_account":"$(storage_account)"}'
      packerVersion: '1.4.4'
      baseImageSource: 'customVhd'
      imageUri: '$imageURL'