# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  client_id: 'clientID'
  tenant_id: 'tenantID'
  subscription_id: 'subID'
  managed_image_resource_group_name: 'app1ResourceGroup'

trigger:
- master

pool:
  vmImage: 'Hosted VS2017'

steps:
- task: PackerBuild@1
  inputs:
    templateType: 'custom'
    customTemplateLocation: 'images\win\vs2019-Server2019-Azure.json'
    customTemplateParameters: '{"client_id":"$(client_id)","client_secret":"$(client_secret)","tenant_id":"$(tenant_id)","subscription_id":"$(subscription_id)","managed_image_prefix":"$(managed_image_prefix)","managed_image_resource_group_name":"$(managed_image_resource_group_name)","PackageLocation":"$(PackageLocation)"}'
    baseImageSource: 'customVhd'
    imageUri: '$imageURL'



